# ICES Quality control sheets

As saved on the ICES network in 2003 and 2004 mostly. Below are the results of a linux `file` command on the list of available qcs-documents, with links to the docs added:

* [anb-78ab.qcs.doc](anb-78ab.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.10, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: Jean-Claude Mah, Revision Number: 19, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 03:02:00, Last Printed: Tue May 20 10:24:00 2003, Create Time/Date: Tue Sep 12 11:13:00 2000, Last Saved Time/Date: Tue May 20 11:21:00 2003, Number of Pages: 1, Number of Words: 560, Number of Characters: 3194, Security: 0

* [anb-89.qcs.doc](anb-89.qcs.doc):         Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: RDuarte, Revision Number: 13, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 01:25:00, Last Printed: Wed Sep 19 14:05:00 2001, Create Time/Date: Fri Sep 15 10:45:00 2000, Last Saved Time/Date: Fri May 23 07:22:00 2003, Number of Pages: 1, Number of Words: 311, Number of Characters: 1685, Security: 0

* [Ane_bisc.qcs.doc](Ane_bisc.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock:  , Author: hl, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 29, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 04:34:00, Last Printed: Wed Sep 19 15:03:00 2001, Create Time/Date: Thu Sep 18 08:47:00 1997, Last Saved Time/Date: Tue Mar 18 10:38:00 2003, Number of Pages: 1, Number of Words: 419, Number of Characters: 2389, Security: 0

* [anp-78ab.qcs.doc](anp-78ab.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: U0882IQU, Revision Number: 26, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 02:46:00, Last Printed: Wed Sep 19 12:47:00 2001, Create Time/Date: Tue Sep 12 10:31:00 2000, Last Saved Time/Date: Thu May 22 14:32:00 2003, Number of Pages: 1, Number of Words: 617, Number of Characters: 3395, Security: 0

* [anp-89.qcs.doc](anp-89.qcs.doc):         Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 12, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 02:23:00, Last Printed: Wed Sep 19 14:05:00 2001, Create Time/Date: Fri Sep 15 10:45:00 2000, Last Saved Time/Date: Tue Mar 11 12:26:00 2003, Number of Pages: 1, Number of Words: 266, Number of Characters: 1519, Security: 0

* [Cod-2224.qcs.doc](Cod-2224.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Cod in Sub-divisions 22-24, Author: Maria Zarecki, Template: Normal.dot, Last Saved By: hd, Revision Number: 3, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 28:00, Last Printed: Mon May 26 10:03:00 2003, Create Time/Date: Mon Jan 19 08:35:00 2004, Last Saved Time/Date: Thu Apr 22 16:20:00 2004, Number of Pages: 1, Number of Words: 426, Number of Characters: 2430, Security: 0

* [Cod-2532.qcs.doc](Cod-2532.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Cod in Sub-divisions 25-32, Author: ..., Template: Normal.dot, Last Saved By: Diane, Revision Number: 2, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 03:00, Last Printed: Wed May 17 10:19:00 2000, Create Time/Date: Mon Jan 19 09:59:00 2004, Last Saved Time/Date: Mon Jan 19 09:59:00 2004, Number of Pages: 1, Number of Words: 506, Number of Characters: 2885, Security: 0

* [Cod-347D.qcs.doc](Cod-347D.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Cod in Sub-area IV (North Sea), Division VIId (Eastern English Channel) and Division IIIa (Skagerrak), Author: Mary Gilmartin, Template: Normal, Last Saved By:  ISH-2000, Revision Number: 3, Name of Creating Application: Microsoft Word 10.0, Last Printed: Thu Sep 18 09:52:00 2003, Create Time/Date: Thu Sep 18 10:17:00 2003, Last Saved Time/Date: Thu Sep 18 10:30:00 2003, Number of Pages: 1, Number of Words: 433, Number of Characters: 2732, Security: 0

* [Cod-7e-k.qcs.doc](Cod-7e-k.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.10, Code page: 1252, Title: Stock: Cod in Divisions VIIe-k , Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: DRV-RH, Revision Number: 36, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 02:22:00, Last Printed: Wed Jul 17 16:09:00 2002, Create Time/Date: Sat Sep 11 12:58:00 1999, Last Saved Time/Date: Wed Jul 17 16:10:00 2002, Number of Pages: 1, Number of Words: 552, Number of Characters: 3148, Security: 0

* [Cod-arct.qcs.doc](Cod-arct.qcs.doc):       Rich Text Format data, version 1, ANSI

* [Cod-coast.qcs.doc](Cod-coast.qcs.doc):      Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock:  North-East Arctic Cod, Author: Mary Gilmartin, Template: Normal, Last Saved By: AFWG, Revision Number: 2, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:00, Last Printed: Mon Apr 28 09:55:00 2003, Create Time/Date: Mon Apr 28 09:56:00 2003, Last Saved Time/Date: Mon Apr 28 09:56:00 2003, Number of Pages: 1, Number of Words: 133, Number of Characters: 762, Security: 0

* [cod-farp.qcs.doc](cod-farp.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Faroe Plateau Cod in Sub-division Vb, Author: Claire Welling, Template: Normal.dot, Last Saved By: Diane, Revision Number: 2, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 23:00, Last Printed: Mon May 26 13:21:00 2003, Create Time/Date: Thu Jan 15 10:56:00 2004, Last Saved Time/Date: Thu Jan 15 10:56:00 2004, Number of Pages: 1, Number of Words: 469, Number of Characters: 2676, Security: 0

* [Cod-iceg.qcs.doc](Cod-iceg.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Cod at Iceland, Author: Bjdrn  varr Steinarsson, Template: Normal.dot, Last Saved By: Diane, Revision Number: 2, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 18:00, Last Printed: Tue May  7 09:09:00 2002, Create Time/Date: Thu Jan 15 13:00:00 2004, Last Saved Time/Date: Thu Jan 15 13:00:00 2004, Number of Pages: 1, Number of Words: 454, Number of Characters: 2589, Security: 0

* [COD-IRIS.QCS.doc](COD-IRIS.QCS.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: Cod in Division VIIa (Irish Sea), Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: rofficer, Revision Number: 4, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 04:00, Last Printed: Tue Sep 18 15:24:00 2001, Create Time/Date: Wed Oct  2 08:35:00 2002, Last Saved Time/Date: Thu Oct  9 10:17:00 2003, Number of Pages: 1, Number of Words: 481, Number of Characters: 2744, Security: 0

* [Cod-kat.qcs.doc](Cod-kat.qcs.doc):        Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Cod - Kattegat, Author: Maria Zarecki, Template: Normal.dot, Last Saved By: Steen Christensen, Revision Number: 5, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 16:00, Last Printed: Thu Apr 22 15:32:00 2004, Create Time/Date: Mon Jan 19 09:30:00 2004, Last Saved Time/Date: Thu Apr 22 15:35:00 2004, Number of Pages: 1, Number of Words: 557, Number of Characters: 3177, Security: 0

* [COD-SCOW.QCS.doc](COD-SCOW.QCS.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Cod in Division VIa (West of Scotland), Author: Mary Gilmartin, Template: Normal, Last Saved By: wim , Revision Number: 5, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 11:00, Last Printed: Wed Sep 19 09:03:00 2001, Create Time/Date: Fri Sep 27 09:05:00 2002, Last Saved Time/Date: Sat Oct 11 07:22:00 2003, Number of Pages: 1, Number of Words: 423, Number of Characters: 2331, Security: 0

* [Cod-skag.qcs.doc](Cod-skag.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 13, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 45:00, Last Printed: Thu Jul 13 12:23:00 2000, Create Time/Date: Fri Jun 21 12:17:00 1996, Last Saved Time/Date: Mon May  6 11:06:00 2002, Number of Pages: 1, Number of Words: 292, Number of Characters: 1667, Security: 0

* [Ghl-arct.qcs.doc](Ghl-arct.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: Greenland halibut in Sub-areas I and II, Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: Nge Hlines, Revision Number: 4, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 15:00, Last Printed: Tue May  7 15:50:00 2002, Create Time/Date: Thu May  1 17:09:00 2003, Last Saved Time/Date: Thu May  1 17:27:00 2003, Number of Pages: 1, Number of Words: 378, Number of Characters: 2156, Security: 0

* [Had-34.qcs.doc](Had-34.qcs.doc):         Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: Kunzlik, Revision Number: 34, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 03:29:00, Last Printed: Tue Jun 18 10:48:00 2002, Create Time/Date: Fri Jun 21 13:25:00 1996, Last Saved Time/Date: Tue Jun 18 11:51:00 2002, Number of Pages: 1, Number of Words: 492, Number of Characters: 2807, Security: 0

* [Had-arct.qcs.doc](Had-arct.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: North-East Arctic Haddock, Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: knutk, Revision Number: 3, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 07:00, Last Printed: Fri May  2 17:00:00 2003, Create Time/Date: Fri May  2 16:59:00 2003, Last Saved Time/Date: Fri May  2 17:00:00 2003, Number of Pages: 1, Number of Words: 430, Number of Characters: 2453, Security: 0

* [Had-faro.qcs.doc](Had-faro.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Faroe Haddock in Division Vb, Author: Maria Zarecki, Template: Normal.dot, Last Saved By: Diane, Revision Number: 2, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 05:00, Last Printed: Mon May 26 13:50:00 2003, Create Time/Date: Thu Jan 15 13:17:00 2004, Last Saved Time/Date: Thu Jan 15 13:17:00 2004, Number of Pages: 1, Number of Words: 411, Number of Characters: 2344, Security: 0

* [Had-icel.qcs.doc](Had-icel.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Icelandic haddock, stock estimates and annual reestimates, Author: Hcskuldur Bjdrnsson, Template: Normal.dot, Last Saved By: Diane, Revision Number: 2, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 03:00, Last Printed: Mon May 26 13:23:00 2003, Create Time/Date: Thu Jan 15 13:42:00 2004, Last Saved Time/Date: Thu Jan 15 13:42:00 2004, Number of Pages: 1, Number of Words: 458, Number of Characters: 2613, Security: 0

* [HAD-IRISde3.QCS.doc](HAD-IRISde3.QCS.doc):    Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: Haddock in Division VIIa (Irish Sea), Author: Mary Gilmartin, Template: Normal, Last Saved By: P-J Schln, Revision Number: 2, Name of Creating Application: Microsoft Word 8.0, Last Printed: Thu May 22 13:58:00 2003, Create Time/Date: Thu May 22 14:47:00 2003, Last Saved Time/Date: Thu May 22 14:47:00 2003, Number of Pages: 1, Number of Words: 354, Number of Characters: 2021, Security: 0

* [HAD-IRIS.QCS.doc](HAD-IRIS.QCS.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Haddock in Division VIIa (Irish Sea), Author: Mary Gilmartin, Template: Normal, Last Saved By: wim , Revision Number: 5, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 14:00, Last Printed: Wed Sep 19 09:18:00 2001, Create Time/Date: Wed Oct  2 09:27:00 2002, Last Saved Time/Date: Sat Oct 11 07:33:00 2003, Number of Pages: 1, Number of Words: 379, Number of Characters: 2087, Security: 0

* [HAD-ROCK.QCS.doc](HAD-ROCK.QCS.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: Haddock in Division VIb (Rockall), Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: rofficer, Revision Number: 5, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 26:00, Last Printed: Wed Sep 19 10:07:00 2001, Create Time/Date: Tue Oct  1 11:35:00 2002, Last Saved Time/Date: Thu Oct  9 10:42:00 2003, Number of Pages: 1, Number of Words: 363, Number of Characters: 2073, Security: 0

* [Her-2532excGoR.qcs.doc](Her-2532excGoR.qcs.doc): Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.10, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: yvowal, Revision Number: 4, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 13:00, Last Printed: Thu Apr 22 10:23:00 2004, Create Time/Date: Thu Apr 22 10:19:00 2004, Last Saved Time/Date: Thu Apr 22 10:28:00 2004, Number of Pages: 1, Number of Words: 409, Number of Characters: 2169, Security: 0

* [Her-30.qcs.doc](Her-30.qcs.doc):         Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: Herring in Sub-division 30, Bothnian Sea  , Author: Maria Zarecki, Template: Normal.dot, Last Saved By: Administrator, Revision Number: 4, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:51:00, Last Printed: Mon May 26 10:17:00 2003, Create Time/Date: Mon Jan 19 08:38:00 2004, Last Saved Time/Date: Tue Apr 20 12:44:00 2004, Number of Pages: 1, Number of Words: 435, Number of Characters: 2483, Security: 0

* [Her-31.qcs.doc](Her-31.qcs.doc):         Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Herring in Sub-division 31, Bothnian Bay , Author: Maria Zarecki, Template: Normal.dot, Last Saved By: TeiAho, Revision Number: 6, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 01:20:00, Last Printed: Wed May 17 09:21:00 2000, Create Time/Date: Mon Jan 19 11:00:00 2004, Last Saved Time/Date: Tue Apr 20 12:44:00 2004, Number of Pages: 1, Number of Words: 458, Number of Characters: 2429, Security: 0

* [Her-3a22.qcs.doc](Her-3a22.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title:  Herring VIa (North), Author: Working Group PC11, Template: Normal.dot, Last Saved By: hm, Revision Number: 3, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 28:00, Last Printed: Tue Apr 23 14:47:00 2002, Create Time/Date: Fri Feb 21 12:43:00 2003, Last Saved Time/Date: Wed Mar 19 16:36:00 2003, Number of Pages: 1, Number of Words: 292, Number of Characters: 1667, Security: 0

* [Her-47d3.qcs.doc](Her-47d3.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: North Sea Herring (Fishing Areas IIIa, IV and VIId), Author: Maria Zarecki, Template: Normal.dot, Last Saved By: Dickey, Revision Number: 14, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:54:00, Last Printed: Wed Mar 19 16:39:00 2003, Create Time/Date: Mon Mar 11 14:49:00 2002, Last Saved Time/Date: Wed Mar 19 16:39:00 2003, Number of Pages: 1, Number of Words: 489, Number of Characters: 2788, Security: 0

* [Her-irls.qcs.doc](Her-irls.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock:  , Author: holger hovgaard, Template: Normal.dot, Last Saved By: Ciaran kelly, Revision Number: 7, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 02:53:00, Last Printed: Tue Apr 23 16:40:00 2002, Create Time/Date: Mon Mar 11 15:57:00 2002, Last Saved Time/Date: Thu Mar 20 14:45:00 2003, Number of Pages: 1, Number of Words: 424, Number of Characters: 2418, Security: 0

* [Her-nirs.qcs.doc](Her-nirs.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: Herring in the North Irish Sea (Manx plus Mourne herring), Author: Richard Briggs, Template: Normal.dot, Last Saved By: Richard D.M. Nash, Revision Number: 10, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:07:00, Last Printed: Wed Mar 19 17:11:00 2003, Create Time/Date: Mon Mar 11 16:00:00 2002, Last Saved Time/Date: Wed Mar 19 17:11:00 2003, Number of Pages: 1, Number of Words: 425, Number of Characters: 2423, Security: 0

* [Her-noss.qcs.doc](Her-noss.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Title: Stock: Norwegian spring-spawning herring, Author: Claire Welling, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 12, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:30:00, Last Printed: Mon May 22 09:43:00 2000, Create Time/Date: Wed Mar 29 11:39:00 2000, Last Saved Time/Date: Wed Mar 20 13:39:00 2002, Number of Pages: 1, Number of Words: 447, Number of Characters: 2147, Security: 0

* [Her-riga.qcs.doc](Her-riga.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1257, Title: Stock: Herring in Sub-divisions 25-29 (incl. Gulf of Riga) and 32, Author: Working Group PC18, Template: Normal.dot, Last Saved By: G.Korlilovs, Revision Number: 5, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 18:00, Last Printed: Wed Apr 21 16:00:00 2004, Create Time/Date: Mon Jan 19 10:39:00 2004, Last Saved Time/Date: Wed Apr 21 16:00:00 2004, Number of Pages: 1, Number of Words: 535, Number of Characters: 3051, Security: 0

* [Herr-riga.qcs.doc](Herr-riga.qcs.doc):      Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: Herring in Sub-divisions 25-29 (incl. Gulf of Riga) and 32, Author: Working Group PC18, Template: Normal, Last Saved By: Tiit Raid, Revision Number: 2, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 05:00, Last Printed: Wed May 17 18:21:00 2000, Create Time/Date: Thu Apr 22 01:00:00 2004, Last Saved Time/Date: Thu Apr 22 01:00:00 2004, Number of Pages: 1, Number of Words: 497, Number of Characters: 2836, Security: 0

* [Her-vasu.qcs.doc](Her-vasu.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Title: Stock: Icelandic summer-spawning herring (Division Va), Author: Maria Zarecki, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 10, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:06:00, Last Printed: Wed Mar 29 12:50:00 2000, Create Time/Date: Wed Mar 29 12:04:00 2000, Last Saved Time/Date: Wed Mar 20 13:44:00 2002, Number of Pages: 1, Number of Words: 444, Number of Characters: 2135, Security: 0

* [Her-vian.qcs.doc](Her-vian.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title:  Herring VIa (North), Author: Working Group PC11, Template: Normal.dot, Last Saved By: Hatfield, Revision Number: 15, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 02:43:00, Last Printed: Thu Mar 20 11:38:00 2003, Create Time/Date: Mon Mar 11 15:03:00 2002, Last Saved Time/Date: Thu Mar 20 11:45:00 2003, Number of Pages: 1, Number of Words: 468, Number of Characters: 2670, Security: 0

* [hke-nrtn.qcs.doc](hke-nrtn.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.10, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: Paulino Lucio, Revision Number: 2, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:00, Last Printed: Wed May 21 10:08:00 2003, Create Time/Date: Wed May 21 10:09:00 2003, Last Saved Time/Date: Wed May 21 10:09:00 2003, Number of Pages: 1, Number of Words: 464, Number of Characters: 2649, Security: 0

* [hke-soth.qcs.doc](hke-soth.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: Mette, Revision Number: 14, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 02:16:00, Last Printed: Mon Aug 25 10:39:00 2003, Create Time/Date: Fri Sep 15 09:45:00 2000, Last Saved Time/Date: Mon Aug 25 10:39:00 2003, Number of Pages: 1, Number of Words: 653, Number of Characters: 4245, Security: 0

* [hom-soth.qcs.doc](hom-soth.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Southern horse mackerel, Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: Diane, Revision Number: 23, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 01:44:00, Last Printed: Mon May  6 12:33:00 2002, Create Time/Date: Mon Sep 20 16:30:00 1999, Last Saved Time/Date: Mon Oct  6 12:42:00 2003, Number of Pages: 1, Number of Words: 486, Number of Characters: 2771, Security: 0

* [Hom-west.qcs.doc](Hom-west.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock:  , Author: Maria Zarecki, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 35, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 03:31:00, Last Printed: Wed Sep 19 15:20:00 2001, Create Time/Date: Fri Sep  5 15:56:00 1997, Last Saved Time/Date: Tue Mar 18 10:49:00 2003, Number of Pages: 1, Number of Words: 490, Number of Characters: 2798, Security: 0

* [Mac-nea.qcs.doc](Mac-nea.qcs.doc):        Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: Western mackerel, Author: PC 24 ICES, Template: Normal, Last Saved By: EltinkA, Revision Number: 50, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 04:07:00, Last Printed: Sun Sep 14 10:02:00 2003, Create Time/Date: Thu Sep 18 16:38:00 1997, Last Saved Time/Date: Sun Sep 14 10:11:00 2003, Number of Pages: 1, Number of Words: 480, Number of Characters: 2736, Security: 0

* [mac-wes.qcs.doc](mac-wes.qcs.doc):        Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: Western mackerel, Author: Mary Gilmartin, Template: Normal, Last Saved By: EltinkA, Revision Number: 17, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:08:00, Last Printed: Wed Sep 19 14:13:00 2001, Create Time/Date: Tue Sep 21 07:41:00 1999, Last Saved Time/Date: Sun Sep 14 10:11:00 2003, Number of Pages: 1, Number of Words: 545, Number of Characters: 3111, Security: 0

* [mgb-8c9a.qcs.doc](mgb-8c9a.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.10, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: Nelida Perez, Revision Number: 30, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 03:18:00, Last Printed: Thu May 22 17:11:00 2003, Create Time/Date: Sun Sep 10 09:52:00 2000, Last Saved Time/Date: Thu May 22 17:11:00 2003, Number of Pages: 1, Number of Words: 452, Number of Characters: 2578, Security: 0

* [mgw-78.qcs.doc](mgw-78.qcs.doc):         Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.10, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: Marina Santurtun, Revision Number: 21, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 02:30:00, Last Printed: Wed May 29 08:45:00 2002, Create Time/Date: Sat Sep  9 21:43:00 2000, Last Saved Time/Date: Sun May 18 15:17:00 2003, Number of Pages: 1, Number of Words: 603, Number of Characters: 3441, Security: 0

* [mgw-8c9a.qcs.doc](mgw-8c9a.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.10, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: Nelida Perez, Revision Number: 36, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 04:54:00, Last Printed: Thu May 22 17:07:00 2003, Create Time/Date: Sun Sep 10 17:59:00 2000, Last Saved Time/Date: Thu May 22 17:11:00 2003, Number of Pages: 1, Number of Words: 450, Number of Characters: 2569, Security: 0

* [nop-nsea.qcs.doc](nop-nsea.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock:  , Author: ICES, Template: Normal, Last Saved By: rn, Revision Number: 6, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 52:00, Last Printed: Thu Jun 20 14:46:00 2002, Create Time/Date: Sat Jun 23 12:11:00 2001, Last Saved Time/Date: Thu Jun 20 15:03:00 2002, Number of Pages: 1, Number of Words: 345, Number of Characters: 1968, Security: 0

* [Pan-sknd.qcs.doc](Pan-sknd.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock:  , Author: Maria Zarecki, Template: Normal.dot, Last Saved By: Diane, Revision Number: 2, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 05:00, Last Printed: Wed Sep 19 12:07:00 2001, Create Time/Date: Thu Jan 22 12:38:00 2004, Last Saved Time/Date: Thu Jan 22 12:38:00 2004, Number of Pages: 1, Number of Words: 422, Number of Characters: 2408, Security: 0

* [Ple-celt.qcs.doc](Ple-celt.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: PC1160, Revision Number: 3, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 07:00, Last Printed: Thu Jul 18 14:34:00 2002, Create Time/Date: Thu Jul 18 14:26:00 2002, Last Saved Time/Date: Thu Jul 18 14:34:00 2002, Number of Pages: 1, Number of Words: 484, Number of Characters: 2665, Security: 0

* [Ple-eche.qcs.doc](Ple-eche.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Plaice in Division VIId (Eastern English Channel)  , Author: Working Group PC20, Template: Normal, Last Saved By: jvigneau, Revision Number: 39, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 03:42:00, Last Printed: Tue Jul 31 13:50:00 2001, Create Time/Date: Sun Oct 13 14:32:00 1996, Last Saved Time/Date: Wed Jun 19 14:29:00 2002, Number of Pages: 1, Number of Words: 508, Number of Characters: 2896, Security: 0

* [Ple-echw.qcs.doc](Ple-echw.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: Departement Zeevisserij, Revision Number: 20, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:06:00, Last Printed: Sun Jul 14 11:58:00 2002, Create Time/Date: Sun Sep 10 14:40:00 2000, Last Saved Time/Date: Sun Jul 14 12:00:00 2002, Number of Pages: 1, Number of Words: 439, Number of Characters: 2507, Security: 0

* [PLE-IRIS.QCS.doc](PLE-IRIS.QCS.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Plaice in Division VIIa (Irish Sea), Author: Mary Gilmartin, Template: Normal, Last Saved By: wim , Revision Number: 5, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 12:00, Last Printed: Wed Sep 19 09:25:00 2001, Create Time/Date: Thu Oct  3 08:59:00 2002, Last Saved Time/Date: Sat Oct 11 07:15:00 2003, Number of Pages: 1, Number of Words: 492, Number of Characters: 2708, Security: 0

* [Ple-kask.qcs.doc](Ple-kask.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: Plaice in Division IIIa , Author: Maria Zarecki, Template: Normal, Last Saved By: clu, Revision Number: 38, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 05:35:00, Last Printed: Thu Jun 20 14:35:00 2002, Create Time/Date: Mon Oct 21 15:19:00 1996, Last Saved Time/Date: Thu Jun 20 14:59:00 2002, Number of Pages: 1, Number of Words: 464, Number of Characters: 2648, Security: 0

* [Ple-nsea.qcs.doc](Ple-nsea.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.10, Code page: 1252, Title: North Sea plaice Quality control sheets, Author: Sieto Verver, Comments: updated for WG2002, Template: Normal.dot, Last Saved By: Sieto Verver, Revision Number: 2, Name of Creating Application: Microsoft Word 9.0, Last Printed: Tue Jul 31 13:20:00 2001, Create Time/Date: Thu Jun 20 10:18:00 2002, Last Saved Time/Date: Thu Jun 20 10:18:00 2002, Number of Pages: 1, Number of Words: 404, Number of Characters: 2308, Security: 0

* [Sai-3a46.qcs.doc](Sai-3a46.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: Saithe in Sub-area VI (West of Scotland and Rockall)  , Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: odd, Revision Number: 23, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 03:03:00, Last Printed: Tue Jul 31 12:54:00 2001, Create Time/Date: Mon Oct  9 15:11:00 2000, Last Saved Time/Date: Wed Jun 19 18:48:00 2002, Number of Pages: 1, Number of Words: 263, Number of Characters: 1504, Security: 0

* [Sai-arct.qcs.doc](Sai-arct.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: North-East Arctic Saithe, Author: Sge Fotland, Template: Normal.dot, Last Saved By: Senter for Ressurs, Revision Number: 2, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 12:00, Last Printed: Tue May  7 15:40:00 2002, Create Time/Date: Mon Mar 31 15:19:00 2003, Last Saved Time/Date: Mon Mar 31 15:19:00 2003, Number of Pages: 1, Number of Words: 513, Number of Characters: 2929, Security: 0

* [Sai-faro.qcs.doc](Sai-faro.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Faroe Saithe in Division Vb, Author: Maria Zarecki, Template: Normal, Last Saved By: Lise Helen Ofstad, Revision Number: 5, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 16:00, Last Printed: Tue May  4 19:52:00 2004, Create Time/Date: Thu Jan 15 13:51:00 2004, Last Saved Time/Date: Tue May  4 19:52:00 2004, Number of Pages: 1, Number of Words: 441, Number of Characters: 2516, Security: 0

* [Sai-icel.qcs.doc](Sai-icel.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock: Icelandic Saithe in Division Va, Author: Maria Zarecki, Template: Normal.dot, Last Saved By: Sigurlur J, Revision Number: 6, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 34:00, Last Printed: Mon Mar 20 13:17:00 2000, Create Time/Date: Thu Jan 15 15:42:00 2004, Last Saved Time/Date: Thu May  6 13:32:00 2004, Number of Pages: 1, Number of Words: 495, Number of Characters: 2827, Security: 0

* [Sai-nsea.qcs.doc](Sai-nsea.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Title: Stock: Saithe in Sub-area IV (North Sea) and Division IIIa (Skagerrak), Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 17, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 02:12:00, Last Printed: Mon Jul 17 09:52:00 2000, Create Time/Date: Tue Oct 14 17:17:00 1997, Last Saved Time/Date: Mon May  6 11:31:00 2002, Number of Pages: 1, Number of Words: 348, Number of Characters: 1989, Security: 0

* [Sai-scrk.qcs.doc](Sai-scrk.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Title: Stock: Saithe in Sub-area VI (West of Scotland and Rockall)  , Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 18, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:02:00, Last Printed: Mon Jul 17 10:00:00 2000, Create Time/Date: Mon Oct 18 12:03:00 1999, Last Saved Time/Date: Mon May  6 11:33:00 2002, Number of Pages: 1, Number of Words: 347, Number of Characters: 1979, Security: 0

* [San-nns.qcs.doc](San-nns.qcs.doc):        Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 13, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:38:00, Last Printed: Mon Jul 17 11:10:00 2000, Create Time/Date: Fri Jun 21 14:11:00 1996, Last Saved Time/Date: Mon May  6 11:35:00 2002, Number of Pages: 1, Number of Words: 261, Number of Characters: 1493, Security: 0

* [san-nsea.qcs.doc](san-nsea.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock:  , Author: Maria Zarecki, Template: Normal, Last Saved By: mv, Revision Number: 21, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 04:36:00, Last Printed: Tue Jul 31 13:34:00 2001, Create Time/Date: Tue Oct 26 09:21:00 1999, Last Saved Time/Date: Thu Jun 20 08:46:00 2002, Number of Pages: 1, Number of Words: 398, Number of Characters: 2274, Security: 0

* [San-scow.qcs.doc](San-scow.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 18, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:50:00, Last Printed: Tue Jul 31 14:29:00 2001, Create Time/Date: Mon Jun 24 08:00:00 1996, Last Saved Time/Date: Mon May  6 12:29:00 2002, Number of Pages: 1, Number of Words: 275, Number of Characters: 1572, Security: 0

* [San-shet.qcs.doc](San-shet.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 15, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:20:00, Last Printed: Tue Jul 31 13:43:00 2001, Create Time/Date: Mon Jun 24 07:23:00 1996, Last Saved Time/Date: Mon May  6 12:31:00 2002, Number of Pages: 1, Number of Words: 273, Number of Characters: 1559, Security: 0

* [San-sns.qcs.doc](San-sns.qcs.doc):        Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 15, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:10:00, Last Printed: Mon Jul 17 12:22:00 2000, Create Time/Date: Mon Jun 24 07:31:00 1996, Last Saved Time/Date: Mon May  6 12:25:00 2002, Number of Pages: 1, Number of Words: 262, Number of Characters: 1498, Security: 0

* [Sar-soth.qcs.doc](Sar-soth.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock:  , Author: Maria Zarecki, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 25, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 02:44:00, Last Printed: Wed Sep 19 14:55:00 2001, Create Time/Date: Mon Sep  8 13:57:00 1997, Last Saved Time/Date: Tue Mar 18 13:50:00 2003, Number of Pages: 1, Number of Words: 401, Number of Characters: 2286, Security: 0

* [Smn-arct.qcs.doc](Smn-arct.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Sebastes mentella in Sub-areas I and II, Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: Diane, Revision Number: 2, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 01:00, Last Printed: Tue May  7 15:50:00 2002, Create Time/Date: Mon May  5 07:58:00 2003, Last Saved Time/Date: Mon May  5 07:58:00 2003, Number of Pages: 1, Number of Words: 400, Number of Characters: 2286, Security: 0

* [Sol-bisc.qcs.doc](Sol-bisc.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.10, Code page: 1252, Title: Stock: Sole in Divisions VIIIa,b  , Author: nichols, Template: Normal.dot, Last Saved By: DRV/RH LAROCHELLE, Revision Number: 43, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 04:38:00, Last Printed: Tue Jul 16 10:19:00 2002, Create Time/Date: Wed Sep 11 06:49:00 1996, Last Saved Time/Date: Tue Jul 16 10:21:00 2002, Number of Pages: 3, Number of Words: 485, Number of Characters: 2770, Security: 0

* [Sol-celt.qcs.doc](Sol-celt.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal.dot, Last Saved By: Departement Zeevisserij, Revision Number: 18, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 01:33:00, Last Printed: Mon Jul 15 14:27:00 2002, Create Time/Date: Wed Feb  9 15:44:00 2000, Last Saved Time/Date: Mon Jul 15 14:27:00 2002, Number of Pages: 1, Number of Words: 451, Number of Characters: 2576, Security: 0

* [Sol-eche.qcs.doc](Sol-eche.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Sole in Division VIId (Eastern English Channel)  , Author: Maria Zarecki, Template: Normal, Last Saved By: Wim Demare, Revision Number: 39, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 05:38:00, Last Printed: Tue Jul 31 13:47:00 2001, Create Time/Date: Mon Oct 21 14:30:00 1996, Last Saved Time/Date: Thu Sep 18 15:35:00 2003, Number of Pages: 1, Number of Words: 527, Number of Characters: 2900, Security: 0

* [Sol-echw.qcs.doc](Sol-echw.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Title: Stock: Sole in Division VIIe (Western English Channel), Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: rsm00, Revision Number: 5, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 12:00, Last Printed: Sat Jul 13 17:14:00 2002, Create Time/Date: Sat Jul 13 17:06:00 2002, Last Saved Time/Date: Sat Jul 13 18:15:00 2002, Number of Pages: 3, Number of Words: 498, Number of Characters: 2842, Security: 0

* [Sol-Kask.qcs.doc](Sol-Kask.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Sole in Division IIIa, Author: Maria Zarecki, Template: Normal.dot, Last Saved By: brm, Revision Number: 4, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 21:00, Last Printed: Tue Apr 20 13:49:00 2004, Create Time/Date: Mon Jan 19 11:46:00 2004, Last Saved Time/Date: Tue Apr 20 13:54:00 2004, Number of Pages: 1, Number of Words: 554, Number of Characters: 3162, Security: 0

* [Sol-nsea.qcs.doc](Sol-nsea.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Title: Stock: North Sea sole , Author: Mary Gilmartin, Comments: updated for 2001 WG by Richard Millner & Sieto Verver, Template: Normal.dot, Last Saved By: rsm00, Revision Number: 14, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 01:09:00, Last Printed: Sun Jun 16 08:34:00 2002, Create Time/Date: Thu Oct 19 13:36:00 2000, Last Saved Time/Date: Sun Jun 16 08:35:00 2002, Number of Pages: 3, Number of Words: 410, Number of Characters: 2341, Security: 0

* [Spr-2232.qcs.doc](Spr-2232.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.10, Code page: 1250, Title: Stock: Sprat in Sub-divisions 22-32  , Author: Eleanor Christiansen, Template: Normal, Last Saved By: W. Grygiel, Revision Number: 6, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 01:05:00, Last Printed: Wed Apr 21 17:14:00 2004, Create Time/Date: Mon Jan 19 11:54:00 2004, Last Saved Time/Date: Wed Apr 21 17:18:00 2004, Number of Pages: 1, Number of Words: 439, Number of Characters: 2507, Security: 0

* [Whb-comb.qcs.doc](Whb-comb.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Title: Stock: Blue whiting combined stock (Sub-areas I-IX and XIV)  , Author: Maria Zarecki, Template: Normal.dot, Last Saved By: Diane Lindemann, Revision Number: 6, Name of Creating Application: Microsoft Word 9.0, Total Editing Time: 27:00, Last Printed: Wed Mar 29 12:55:00 2000, Create Time/Date: Thu Apr 26 13:55:00 2001, Last Saved Time/Date: Wed Mar 20 13:48:00 2002, Number of Pages: 1, Number of Words: 432, Number of Characters: 2075, Security: 0

* [whg-47d.qcs.doc](whg-47d.qcs.doc):        Composite Document File V2 Document, Little Endian, Os: Windows, Version 4.0, Code page: 1252, Title: Stock: Whiting in Sub-area IV (North Sea) and Division VIId (Eastern English Channel) , Author: Mary Gilmartin, Template: Normal.dot, Last Saved By: Computing, Revision Number: 21, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 05:24:00, Last Printed: Thu Jun 20 15:01:00 2002, Create Time/Date: Tue Oct 19 19:29:00 1999, Last Saved Time/Date: Thu Jun 20 16:12:00 2002, Number of Pages: 3, Number of Words: 509, Number of Characters: 2906, Security: 0

* [whg-7e-k.qcs.doc](whg-7e-k.qcs.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.0, Code page: 1252, Title: Stock:, Author: maria zarecki, Template: Normal, Last Saved By: wgssds, Revision Number: 17, Name of Creating Application: Microsoft Word 8.0, Total Editing Time: 01:27:00, Last Printed: Thu Jul 18 07:52:00 2002, Create Time/Date: Sun Sep 10 18:15:00 2000, Last Saved Time/Date: Thu Jul 18 07:53:00 2002, Number of Pages: 3, Number of Words: 431, Number of Characters: 2458, Security: 0

* [WHG-IRIS.QCS.doc](WHG-IRIS.QCS.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Whiting in Division VIIa (Irish Sea) , Author: Mary Gilmartin, Template: Normal, Last Saved By: wim , Revision Number: 5, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 10:00, Last Printed: Wed Sep 19 09:21:00 2001, Create Time/Date: Wed Oct  2 15:38:00 2002, Last Saved Time/Date: Sat Oct 11 07:52:00 2003, Number of Pages: 1, Number of Words: 409, Number of Characters: 2250, Security: 0

* [WHG-SCOW.QCS.doc](WHG-SCOW.QCS.doc):       Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1252, Title: Stock: Whiting in Division VIa (West of Scotland)  , Author: PC 24 ICES, Template: Normal, Last Saved By: wim , Revision Number: 5, Name of Creating Application: Microsoft Word 10.0, Total Editing Time: 09:00, Last Printed: Wed Sep 19 09:00:00 2001, Create Time/Date: Fri Sep 27 10:12:00 2002, Last Saved Time/Date: Sat Oct 11 07:56:00 2003, Number of Pages: 1, Number of Words: 456, Number of Characters: 2512, Security: 0
